### ISSUE TITLE
フォーマットがおかしい

### ISSUE THREAD

**Issue by dcbrown16** [MicrosoftDocs/azure-docs.ja-jp#4957] opened 2020-07-10 06:33 UTC
このページにおいて、複数の箇所で必要以上なテキストがリンクになっています。
修正願います。

---
#### ドキュメントの詳細

⚠ *このセクションを編集しないでください。 docs.microsoft.com で必須です ➟ GitHub の問題のリンク。*

* ID: 1c1b0e78-b64a-7e49-fe47-ad401aacb79c
* Version Independent ID: 546a889a-5a08-1a9d-0653-68446a55e693
* Content: [仮想ネットワーク規則 - Azure Database for PostgreSQL - Single Server](https://docs.microsoft.com/ja-jp/azure/postgresql/concepts-data-access-and-security-vnet#only-one-geographic-region)
* Content Source: [articles/postgresql/concepts-data-access-and-security-vnet.md](https://github.com/MicrosoftDocs/azure-docs.ja-jp/blob/master/articles/postgresql/concepts-data-access-and-security-vnet.md)
* Service: **postgresql**
* GitHub Login: @rachel-msft
* Microsoft Alias: **raagyema**

**Comment by rachel-msft** [comment] 2020-07-10 22:35
Hi @dcbrown16. Thank you for the feedback. The translator shows "On this page, there are more text links than necessary in multiple places. Please correct it." Could you please help me better understand what you mean? Could you provide an example of the issue and how you would like to see it changed?

**Comment by dcbrown16** [comment] 2020-07-12 23:03
@rachel-msft it's just a localization issue, some markup is missing somewhere on the Japanese page so half of the page is hypertext. There are several occurrences of this that need to be fixed, I couldn't figure out what the issue was:
![image](https://user-images.githubusercontent.com/34466884/87258536-2596e180-c459-11ea-9ad6-56748d871023.png)

**Comment by JasonWHowell** [comment] 2020-07-13 23:16
@nokura could you please take a look.

**Comment by JasonWHowell** [comment] 2020-07-13 23:16
#reassign:nokura

**Comment by JasonWHowell** [comment] 2020-07-13 23:16
#assign:nokura

**Comment by JasonWHowell** [comment] 2020-07-13 23:19
The problem is in the markdown on line 28, we have an anchor, but the docs site recently stopped respecting self-closing anchor tags in HTML. 
<a name="anch-terminology-and-description-82f" />

Two ways to resolve are 
1. Remove line 28 
2. Change it to a separate closing tag
```
<a name="anch-terminology-and-description-82f"></a>
```

**Comment by JasonWHowell** [comment] 2020-07-13 23:21
There are others for example: 
Line 48: ```<a name="anch-benefits-of-a-vnet-rule-68b" />```
Line 72: ```<a name="anch-details-about-vnet-rules-38q" />```

**Comment by JasonWHowell** [comment] 2020-07-13 23:27
Internal Microsoft: see also https://ceapex.visualstudio.com/Engineering/_workitems/edit/228574

**Comment by JasonWHowell** [comment] 2020-07-13 23:53
There was only one of the problem anchors in the English version, and I fixed that in MicrosoftDocs/Azure-docs-pr#122234. The other two are not in the en-us version, so it would help to understand if the localization workflow should copy those tags from en-us or how that works. Or if **azure-docs.ja-jp** needs to be edited manually by hand to synchronize it.

**Closed** 2020-07-14 11:12 UTC

**Comment by JasonWHowell** [comment] 2020-07-14 15:30
#reopen this is still pending help from the localization team.
