### ISSUE TITLE
Please fix the table width

### ISSUE THREAD

**Issue by KeiroKamioka0000** [MicrosoftDocs/azure-docs.ja-jp#1991] opened 2019-01-31 04:00 UTC
As I posted on another document, please consider to fix the width of the 'column'.
Japanese strings may require more width than original English, it hard to read it.
Thanks,

---
#### ドキュメントの詳細

⚠ *このセクションを編集しないでください。 docs.microsoft.com で必須です ➟ GitHub の問題のリンク。*

* ID: bfb6e003-773e-035b-984b-369d439b56b4
* Version Independent ID: d8c16d2e-4448-741e-12b1-fa8d0b4f707f
* Content: [Azure Application Insights アプリのデータを表示する](https://docs.microsoft.com/ja-jp/azure/azure-monitor/platform/app-insights-connector)
* Content Source: [articles/azure-monitor/platform/app-insights-connector.md](https://github.com/MicrosoftDocs/azure-docs.ja-jp/blob/live/articles/azure-monitor/platform/app-insights-connector.md)
* Service: **log-analytics**
* GitHub Login: @MGoedtel
* Microsoft Alias: **magoedte**

**Comment by LisandroSu** [comment] 2019-01-31 20:33
Hello, @KeiroKamioka0000 
 
Thank you for your feedback.
 
We are actively reviewing your comments and will get back to you soon.

Kind regards,
Microsoft DOCS International Team

**Comment by LisandroSu** [comment] 2019-01-31 20:35
Hi, @SunnyDeng 

This issue is like #1846 the width of the columns makes it difficult to read in Japanese.

Thanks!

**Comment by CeciAc** [comment] 2019-03-11 18:11
@SunnyDeng 
Please, confirm if we can close this issue since is related to #1846

**Comment by SunnyDeng** [comment] 2019-03-11 22:42
Hello, @KeiroKamioka0000 
The table looks good to us now. I am closing this ISSUE. But please kindly try at your end and let us know if you still reproduce the issue.
![image](https://user-images.githubusercontent.com/8811264/54162810-24444780-4414-11e9-8c40-13895a477c6c.png)
Thank you for your support!
-sunny

**Closed by SunnyDeng** 2019-03-11 22:42 UTC
Labels: Technical Issue
